fix: Multiple image extension type handler
heartexlabs/label-studio-converter pull request #156
Opened 2022-11-15 06:05 UTC by p0p4k

image extension/s - single string or comma separated list to search, eg. '.jpeg' or '.jpg, .png' usage: yolo.py --image-ext .jpg, .png, .jpeg

2022-11-24 00:56 UTC, makseq requested changes
Thanks for this great PR! 
It would be great if you could add a test for yolo import also!
Do you mind if I ask you to help here?

2022-11-24 03:00 UTC, p0p4k commented
Ill add some tests ASAP. I don't mind being asked for help; as long as it is in my capacity to get it done, I will do it.

2022-12-07 10:32 UTC, p0p4k commented
@makseq I wrote some simple basic tests and tried it out. Made some silly typos here and there and fixed the code finally.
Please have a look. Thanks.

2022-12-20 03:20 UTC, makseq approved these changes

2022-12-20 03:20 UTC, merged