Add agreement to csv\tsv\json_min
heartexlabs/label-studio-converter pull request #70
Opened 2021-11-16 15:49 UTC by KonstantinKorotaev

2021-11-17 16:28 UTC, niklub requested changes

2021-11-17 16:28 UTC, niklub commented on label_studio_converter/converter.py
> +                'agreement': task.get('agreement'),
we shouldn't include that if agreement=null, in case of the open source

2021-11-17 16:44 UTC, makseq approved these changes

2021-11-18 22:27 UTC, niklub requested changes

2021-11-18 22:27 UTC, niklub commented on setup.py
> +with open('label_studio_converter/__init__.py') as f:
don't use relative paths, instead
```
os.path.join(os.path.dirname(__file__), '__init__.py')
```

2021-11-18 22:41 UTC, niklub commented on label_studio_converter/converter.py
> +                'agreement': task.get('agreement'),
```
if 'agreement' in task:
    data['agreement'] = task['agreement']
```

2021-11-22 18:44 UTC, closed without merging